name: Build Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.1"

      - name: Decode keystore
        run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Pub Get Packages
        run: flutter pub get
        
      - name: Build apk
        run: flutter build apk --flavor production --target lib/main_production.dart

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/**"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true